### ISSUE TITLE
More consistent location for the c++ library (native build) + another readme suggestion

### ISSUE THREAD

**Issue by pillowtrucker** [h1romas4/libymfm.wasm#2]
I've found that I have to set `build.rs` to this if I want to use your library as a library in my project, because the CWD is actually set to the workspace root of my package for some reason:
```rust    
let dir = env::var("CARGO_MANIFEST_DIR").unwrap();
println!("cargo:rustc-link-search=native={}/dist", dir);
```

Also the cmake build instructions could have been simpler:
```
cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/x86-64.cmake -S . -B build
cmake --build build --parallel $(nproc)
```

**Comment by h1romas4** [comment]
Thanks for your suggested improvements!
I have committed to the fix.

**Comment by pillowtrucker** [comment]
Thank you, and thanks for your hard work on this project!
I also have it compiling on github CI on Mac and Windows now, but I haven't really tested if it works at runtime on those systems. Let me know if you're interested and I'll make a PR
